scope({c0_Server:2, c0_utilization:2});
defaultScope(1);
intRange(-8, 7);
stringLength(16);

c0_HighRT = Clafer("c0_HighRT").withCard(0, 1);
c0_ExtraServers = Clafer("c0_ExtraServers").withCard(0, 1);
c0_Underloaded = Clafer("c0_Underloaded").withCard(0, 1);
c0_Status = Clafer("c0_Status").withCard(1, 1);
c0_sumUtilization = c0_Status.addChild("c0_sumUtilization").withCard(1, 1);
c0_averageUtilization = c0_Status.addChild("c0_averageUtilization").withCard(1, 1);
c0_ServerRemover = Clafer("c0_ServerRemover").withCard(0, 1);
c0_ServerLauncher = Clafer("c0_ServerLauncher").withCard(0, 1);
c0_Server = Abstract("c0_Server");
c0_utilization = c0_Server.addChild("c0_utilization").withCard(1, 1);
c0_Manager = Abstract("c0_Manager");
c0_activeServers = c0_Manager.addChild("c0_activeServers").withCard(1, 1);
c0_maxServers = c0_Manager.addChild("c0_maxServers").withCard(1, 1);
c0_responseTime = c0_Manager.addChild("c0_responseTime").withCard(1, 1);
c0_Srv1 = Clafer("c0_Srv1").withCard(1, 1);
c0_Srv2 = Clafer("c0_Srv2").withCard(1, 1);
c0_Mngr = Clafer("c0_Mngr").withCard(1, 1);
c0_Status.addConstraint(equal(joinRef(join($this(), c0_sumUtilization)), sum(join(global(c0_Server), c0_utilization))));
c0_Status.addConstraint(equal(joinRef(join($this(), c0_averageUtilization)), div(joinRef(join($this(), c0_sumUtilization)), card(global(c0_Server)))));
c0_sumUtilization.refToUnique(Int);
c0_averageUtilization.refToUnique(Int);
Constraint(and(and(and(and(ifThenElse(greaterThanEqual(joinRef(join(global(c0_Manager), c0_responseTime)), constant(75)), one(global(c0_HighRT)), none(global(c0_HighRT))), ifThenElse(lessThan(joinRef(join(global(c0_Manager), c0_activeServers)), joinRef(join(global(c0_Manager), c0_maxServers))), one(global(c0_ExtraServers)), none(global(c0_ExtraServers)))), ifThenElse(lessThan(joinRef(join(global(c0_Status), c0_averageUtilization)), constant(30)), one(global(c0_Underloaded)), none(global(c0_Underloaded)))), ifThenElse(and(some(global(c0_HighRT)), some(global(c0_ExtraServers))), one(global(c0_ServerLauncher)), none(global(c0_ServerLauncher)))), ifThenElse(and(some(global(c0_Underloaded)), greaterThan(joinRef(join(global(c0_Manager), c0_activeServers)), constant(1))), one(global(c0_ServerRemover)), none(global(c0_ServerRemover)))));
c0_ServerRemover.addConstraint(none(global(c0_ServerLauncher)));
c0_ServerLauncher.addConstraint(none(global(c0_ServerRemover)));
c0_utilization.refToUnique(Int);
c0_activeServers.refToUnique(Int);
c0_maxServers.refToUnique(Int);
c0_responseTime.refToUnique(Int);
c0_Srv1.extending(c0_Server);
c0_Srv1.addConstraint(equal(joinRef(join($this(), c0_utilization)), constant(10)));
c0_Srv2.extending(c0_Server);
c0_Srv2.addConstraint(equal(joinRef(join($this(), c0_utilization)), constant(20)));
c0_Mngr.extending(c0_Manager);
c0_Mngr.addConstraint(equal(joinRef(join($this(), c0_activeServers)), constant(1)));
c0_Mngr.addConstraint(equal(joinRef(join($this(), c0_maxServers)), constant(4)));
c0_Mngr.addConstraint(equal(joinRef(join($this(), c0_responseTime)), constant(20)));
